#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run Composer fix script first (auto-fixes issues)
composer fix

# Run Composer lint script (ensures no issues remain)
composer lint

# Run Laravel tests
./vendor/bin/sail artisan test
